name: Test

on:
  push:
  pull_request:

jobs:
  ci:
    name: Test on PHP${{ matrix.php-version }} Swoole-${{ matrix.sw-version }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-version: [ '7.3', '7.4', '8.0' ]
        sw-version: [ 'v4.5.11', 'v4.6.7', 'v4.7.0', 'master' ]
      max-parallel: 12
      fail-fast: false
    env:
      SW_VERSION: ${{ matrix.sw-version }}
      MYSQL_VERSION: '5.7'
      YASD_VERSION: 'v0.3.9'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
          extensions: redis, pdo, pdo_mysql, bcmath
          ini-values: opcache.enable_cli=1
          coverage: none
      - name: Setup Swoole
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev
          wget https://github.com/swoole/swoole-src/archive/${SW_VERSION}.tar.gz -O swoole.tar.gz
          mkdir -p swoole
          tar -xf swoole.tar.gz -C swoole --strip-components=1
          rm swoole.tar.gz
          cd swoole
          phpize
          ./configure --enable-openssl --enable-http2 --enable-swoole-curl --enable-swoole-json
          make -j$(nproc)
          sudo make install
          sudo sh -c "echo extension=swoole > /etc/php/${{ matrix.php-version }}/cli/conf.d/swoole.ini"
          sudo sh -c "echo swoole.use_shortname='Off' >> /etc/php/${{ matrix.php-version }}/cli/conf.d/swoole.ini"
          php --ri swoole
      - name: Setup Yasd
        run: |
          sudo apt-get update
          sudo apt-get install libboost-all-dev
          wget https://github.com/swoole/yasd/archive/${YASD_VERSION}.tar.gz -O yasd.tar.gz
          mkdir -p yasd
          tar -xf yasd.tar.gz -C yasd --strip-components=1
          rm yasd.tar.gz
          cd yasd
          phpize
          ./configure
          make -j$(nproc)
          sudo make install
          sudo sh -c "echo extension=yasd > /etc/php/${{ matrix.php-version }}/cli/conf.d/yasd.ini"
          php --ri yasd
      - name: Setup Packages
        run: composer update -o
      - name: Setup Mysql
        run: bash ./.github/scripts/setup.mysql.sh
      - name: Run Test Cases
        run: composer test